# Generated by Django 2.2.7 on 2019-11-12 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentsLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=3)),
                ('prediction', models.FloatField()),
                ('real_price', models.FloatField()),
                ('day', models.IntegerField()),
                ('test_case', models.IntegerField()),
            ],
            options={
                'ordering': ['-day'],
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dollar_count', models.FloatField(default=11000000.0)),
                ('tenge', models.FloatField(default=0.0)),
                ('created_at', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='RateList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usd', models.FloatField()),
            ],
        ),
    ]
