# Generated by Django 2.2.7 on 2019-11-12 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('government', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratelist',
            options={'ordering': ('-id',)},
        ),
    ]
