# Generated by Django 2.2.7 on 2019-11-12 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('government', '0002_auto_20191112_1225'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratelist',
            options={'ordering': ('id',)},
        ),
        migrations.AddField(
            model_name='agentslog',
            name='current',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
