# Generated by Django 2.2.7 on 2019-12-10 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('government', '0005_agentslog_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentsState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('day', models.IntegerField()),
                ('test_case', models.IntegerField()),
                ('is_seller', models.BooleanField(default=False)),
                ('cost', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='agentslog',
            name='buyer',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='agentslog',
            name='from_government',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='agentslog',
            name='seller',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
