# Generated by Django 2.2.7 on 2019-12-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('government', '0007_agentsstate_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentslog',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
